In [1]:
'''
Model aims to take input bottlenecks, append them together and apply 
machine learning models

'''

## input reading data
#####Automation
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import cv2
from os import listdir
from os.path import isfile, join
import os
from sklearn.cross_validation import train_test_split
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix
from sklearn import svm
import time
import pickle
import glob


In [2]:
file_list = []
for filename in glob.iglob('/home/hitesh/Downloads/capstone/bottleneck/**/*.txt'):
    file_list.append(filename)
    

In [2]:
# if using csv file
#result_array = pd.read_csv('/home/hitesh/Downloads/capstone/saveD_csv_data.csv')
#result_array = result_array.drop('Unnamed: 0', axis= 1)


In [5]:
## retrieving data from bottle necks

# read data and put it in  an array
result_array = np.empty((0, 2048))

for i in file_list:
    data1 = pd.read_csv(i, header= None, sep= ',' )
    result_array = np.append(result_array,data1,axis= 0)
        
        


In [6]:

result_array.shape

(10142, 2048)

In [13]:
##labels data

sum_p = 0 
result_labels = np.empty((0, 1))
location = '/home/hitesh/Downloads/capstone/bottleneck'
folder_list = listdir(location)
for folder in folder_list :
    folder_loc = location+ '/'+folder
    a_length = listdir(folder_loc)
    p_count_lenth = len(a_length)
    sum_p = sum_p + p_count_lenth

    label_repeat = np.repeat(folder,p_count_lenth).reshape(-1,1)
    result_labels = np.append(result_labels,label_repeat, axis= 0)
    


    

In [14]:
result_labels.shape

(10142, 1)

In [16]:
##train test split

X_train , X_test , y_train, y_test = train_test_split(result_array,result_labels,train_size = 0.8,test_size = 0.2, random_state = 6)

In [17]:
###svm model

start = time.time()
model = svm.SVC()
model.fit(X_train , y_train)
print model.score(X_train,y_train)
print model.score(X_test,y_test)
stop = time.time()
print(stop - start)




/home/hitesh/anaconda/lib/python2.7/site-packages/sklearn/svm/base.py:514: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y_ = column_or_1d(y, warn=True)


0.9181560458523358
0.897486446525382
334.669705868


In [18]:

# SVM model prediction analysis

y_pred_svm = model.predict(X_test)

print confusion_matrix(y_pred_svm,y_test)

print precision_score(y_test, y_pred_svm, average="macro")

   

[[34  0  0 ...  0  0  0]
 [ 0 18  0 ...  0  0  0]
 [ 0  0 18 ...  0  1  0]
 ...
 [ 0  0  0 ... 13  0  0]
 [ 0  0  0 ...  0 11  0]
 [ 0  0  0 ...  0  0 14]]
0.8974109628845554


/home/hitesh/anaconda/lib/python2.7/site-packages/sklearn/metrics/classification.py:1074: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [19]:
##naive bayes model
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train , y_train)
print nb.score(X_train,y_train)
print nb.score(X_test,y_test)


/home/hitesh/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:515: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.9264143966473561
0.8605224248398226


In [20]:
# naive bayes

y_pred_naive = nb.predict(X_test)

print confusion_matrix(y_pred_naive,y_test)

print precision_score(y_test, y_pred_naive, average="macro")


[[32  0  0 ...  0  0  0]
 [ 0 16  0 ...  0  0  0]
 [ 0  0 16 ...  0  1  0]
 ...
 [ 0  0  0 ... 14  0  0]
 [ 0  0  0 ...  0  9  0]
 [ 0  0  0 ...  0  0 12]]
0.8738915104288661


In [113]:
# save the model to disk
filename = 'finalized_model.sav'
pickle.dump(model, open(filename, 'wb'))
 
# some time later...
 


In [115]:
##loading moddel

loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(X_test, y_test)
print(result)

0.897486446525382


In [117]:
##write csv data for future purposes
result_array2 = pd.DataFrame(result_array)
result_array2.to_csv("saveD_csv_data.csv")

u'/home/hitesh'